# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Robot See Robot Do
tagline:          'Robot See Robot Do'
description:      'MRAC WORKSHOP'
baseurl: "/robot_see_robot_do/" # the subpath of your site, e.g. /blog
url: "https://le-ar-n.github.io/robot_see_robot_do/" # the base hostname & protocol for your site, e.g. http://example.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/augmentedfabricationlab/robot_see_robot_do

plugins:
  - jekyll-feed

collections:
  sessions:
    output: true
